### ISSUE TITLE
GeoLocationCollector crash

### ISSUE THREAD

**Issue by edbaster** [open-pay/openpay-ios#2]
Hi, I'm constantly getting this crash in the **GeoLocationCollector** class, specifically in the 
_-[GeoLocationCollector storeLocation:]_.
It appears that this is a class included in the **libDeviceCollector** static library.
Any suggestions? Maybe an update to this library?

**Comment by igrijalva** [comment]
Hi! Thanks for the information, we will review the problem and soon we will offer a solution.

**Comment by igrijalva** [comment]
The warning message comes from a third-party library, the update will come soon.
